# Generated by Django 3.2.6 on 2021-09-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollutantentry',
            name='year',
            field=models.IntegerField(),
        ),
    ]
