# Generated by Django 3.2.6 on 2021-09-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0002_alter_pollutantentry_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollutantentry',
            name='country',
        ),
    ]
