# Generated by Django 3.2.6 on 2021-09-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0002_auto_20210914_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutantentry',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='airpollution.country'),
            preserve_default=False,
        ),
    ]
