# Generated by Django 3.2.6 on 2021-09-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0003_pollutantentry_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollutantentry',
            name='pollution_level',
            field=models.FloatField(),
        ),
    ]
