# Generated by Django 3.2.6 on 2021-09-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0003_remove_pollutantentry_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.AddField(
            model_name='country',
            name='iso_code',
            field=models.CharField(default='AA', max_length=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
