# Generated by Django 3.2.6 on 2021-09-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0005_pollutant_limit_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='color',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
