# Generated by Django 3.2.6 on 2021-10-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0006_country_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutant',
            name='color',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
