# Generated by Django 3.2.6 on 2021-09-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_myapp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapp',
            name='url',
            field=models.CharField(default='/airpollution', max_length=30),
            preserve_default=False,
        ),
    ]
