# Generated by Django 3.2.6 on 2021-10-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finances', '0003_auto_20211011_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
