# Generated by Django 3.2.6 on 2021-10-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finances', '0004_auto_20211011_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='repetition_interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'N/A'), (2, 'DAYS'), (3, 'WEEKS'), (4, 'MONTHS'), (5, 'YEARS')], default=1),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='repetition_interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'N/A'), (2, 'DAYS'), (3, 'WEEKS'), (4, 'MONTHS'), (5, 'YEARS')], default=1),
        ),
    ]
